### ISSUE TITLE
点击切换日/夜间按钮之后，屏幕全黑了

### ISSUE THREAD

**Issue by okadaNana** [fython/Blackbulb#1]
设备：华为 H30-C00
系统：Android 4.3
详细情况：
AS 编译之后，安装到手机。点击日/夜间切换按钮，屏幕全黑，看不清屏幕。不过状态栏没有收到影响，正常显示。滑动 seekbar，设置为最大，情况还是这样。
图片：
![图片](https://cloud.githubusercontent.com/assets/10471241/12711147/67af14e0-c8f8-11e5-940b-096b9e7bafb0.png)

**Comment by fython** [comment]
@owenmike 请问，开启了覆盖状态栏模式也是这样吗？

**Comment by owenmike** [comment]
开启了覆盖状态栏模式是全都是黑的

**Comment by fython** [comment]
如果不开呢？
