### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by aharris88** [fython/Blackbulb#22]
It would be great to have a widget that you could add to the homescreen to turn on night mode.

**Comment by aharris88** [comment]
Or some people might also like a widget that is a slider.

**Comment by fython** [comment]
It's a good idea. I will do this.

**Comment by fython** [comment]
I made a toggle button (shortcut) for Night Screen. However, I found it not easy to make slider as a widget. Sorry that I only finished one type of widgets.

**Comment by aharris88** [comment]
Nice! 👍

I saw that in this commit (https://github.com/fython/Blackbulb/commit/d6d100f5ffab553bb33d904b74348fe3844c5ec8) you used a different icon for the widget.

I think it would be good to use the normal app icon. I really like the normal icon because it looks like a sun and moon. This icon is just a hand, which is not as descriptive. It would also be nice if the icon switch between 2 different icons to show if night mode is currently on or off.

**Comment by aharris88** [comment]
@fython Any thoughts on the widget icon?

**Comment by fython** [comment]
I prefer the present icon. But I wonder what major opinion is. However, I didn't build any community :\

**Comment by aharris88** [comment]
Yeah, I wonder...
