### ISSUE TITLE
Missing icon in status bar when Night Screen is paused

### ISSUE THREAD

**Issue by M2ck** [fython/Blackbulb#25]
Currently when Night Screen is working, an icon appears in status bar. IMO it should be logic to get an icon in status bar also when NS is paused.

**Comment by fython** [comment]
Could you tell me your Android version? Missing icon problem didn't happen in my phone.

**Comment by M2ck** [comment]
My Android version is MM 6.0.1 (OnePlus X).

**Comment by M2ck** [comment]
I've noticed something : when app is paused and I lock and then unlock screen, the status bar icon reappears, this is an odd behavior. 
Anyway this information will be perhaps helpful for fix this (minor) bug.

**Comment by TPS** [comment]
Workaround for OSs w/ notification tiles: _that_ works just fine.

**Comment by ArchieMeng** [comment]
Can u take a screenshot? Both status bar and notification? The only thing I know is that previous (running) notification canceled by call NotificationManager before create the paused notification.

**Comment by user8446** [comment]
I have noticed that if you pause via the notification then the notification persists *only* if the night screen settings menu is not open. If the night screen menu is also open and you pause via the notification then the notification goes away.

**Comment by fython** [comment]
@user8446 When the night screen menu is open, paused notification won't show because you can restart it from menu.

**Comment by hurzl** [comment]
For me the notification goes off when I pause night mode. On 2 devices with LineageOS 15.1 and 14.1. So I have to restart the app every time I want to enable it. And the Auto mode switch (?) does nothing at all.
