### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by wuchangfeng** [fython/Blackbulb#3]
你好，个人对这个应用很感兴趣，看了你的源代码。发现不是太能理解。能给个大概的开发流程或者设计思路==

想自己实现个，因为自己的狗摩夜间模式效果太差==

**Comment by fython** [comment]
Activity 作为设置 UI 界面，用 Service 做“遮罩”服务。
遮罩就需要用到 WindowsManager 了，创建一个 View 并设置大小、颜色、透明度，设置好优先级比较高的 Flag 保证它在屏幕中浮于其他界面即可。

**Comment by wuchangfeng** [comment]
十分感谢，最近刚好学习到桌面小部件开发这块。
