### ISSUE TITLE
Feature request: Timer for activating/deactivating

### ISSUE THREAD

**Issue by user8446** [fython/Blackbulb#30]
A timer to automatically activate/deactivate. Is this on the roadmap?
Thank you for the development!

**Comment by TPS** [comment]
@user8446 It'd much more helpful if issue title was something like <kbd>Feature Request: Activating/Deactivating Timer</kbd>

**Comment by user8446** [comment]
Changed, thanks!

**Comment by fython** [comment]
This is really a good idea. I will try it.

**Comment by TPS** [comment]
@fython Could this also include de/activating on certain activities, such as startup or app installation?

**Comment by fython** [comment]
@TPS Some system events can't be detected. But I will try it when I know the way to make it out.

**Comment by fython** [comment]
Finally, I made a timer to automatically activate/deactivate (4dd9411c166cf2c6723282a4c22932852822e9c0).

You can download and try it: https://github.com/fython/Blackbulb/releases/tag/1.3.0-beta.1

BTW, I open the Play Store beta channel of this app. You can join it and receive the latest version.
https://play.google.com/apps/testing/info.papdt.blackblub

**Comment by user8446** [comment]
Thank you! Testing now...
