### ISSUE TITLE
Replacing topbar with toolbar

### ISSUE THREAD

**Issue by veyndan** [fython/Blackbulb#31]
In [this commit](https://github.com/fython/Blackbulb/commit/7d3fba1174c0e29bf08712dff857fe1550fbe1a5) I replaced the top bar with the toolbar and it was merged. However in the subsequent two commits, it was reverted back to using the top bar, the two commits being [this one](https://github.com/fython/Blackbulb/commit/0762b2b4dd77a53e1ba6686962adedad731c5f07) and [this one](https://github.com/fython/Blackbulb/commit/39bccce7127c61a2ca4bef2af879ac26465d9e40).

What happened? I feel that you didn't properly check the merge conflicts and hence all the work was overridden.

**Comment by fython** [comment]
Oops, I am sorry that I didn't notice the commit was overriden. I will consider to replace topbar with toolbar.

**Comment by fython** [comment]
Night Screen's UI will be re-designed in the future. This issue is out-of-date. Thanks for your contribution.
