### ISSUE TITLE
Normal Mode bug: Install button can't be clicked.

### ISSUE THREAD

**Issue by Garfield550** [fython/Blackbulb#32]
Android: LineageOS 14.1 (Android 7.1.1)

![Screenshot](https://cloud.githubusercontent.com/assets/3471836/22851915/8684a330-f06b-11e6-9dd9-692a3f7572a7.png)

Video: 
https://youtu.be/9B9YgdSXpCY

**Comment by fython** [comment]
This is not a bug. This is a system feature.

**Comment by Garfield550** [comment]
@fython What's feature?

**Comment by fython** [comment]
@Garfield550 It prevents third party applications from fooling you into installing another application. Related link: https://blog.lookout.com/blog/2010/12/09/android-touch-event-hijacking/

**Comment by fython** [comment]
@Garfield550 You may find it also unable to grant permission for apps in Android 6.0 while Night Screen is on the normal mode.

**Comment by Garfield550** [comment]
@fython  Thanks!
