### ISSUE TITLE
[bug] v1.3.0.beta1 auto mode settings cropped in portrait

### ISSUE THREAD

**Issue by user8446** [fython/Blackbulb#33]
![screenshot_20170613-131545](https://user-images.githubusercontent.com/18019245/27095677-8a3389ca-503c-11e7-97b7-5b8588598938.png)

**Comment by fython** [comment]
Thanks for your feedback. Fixed 3d9fbcd701357ccf888ca95eb5a04482a0c214e7.
You can try the latest version of Night Screen. It has been released in Github Releases.

**Comment by user8446** [comment]
Confirmed fixed with v1.3.0 on an android 6.0.1 device, thanks fython
