### ISSUE TITLE
[建议]求支持“遮蔽导航栏”

### ISSUE THREAD

**Issue by lef-est** [fython/Blackbulb#4]
只是遮蔽状态栏的话 overlay mode似乎也不是很有意义…依旧闪瞎眼
很多用户选择dimmer app的标准线就是看有没有遮蔽导航栏的功能呢

**Comment by fython** [comment]
暂未找到遮蔽导航栏的方法，而且忙于学业，很抱歉需要等候一段时间再去考虑做出来这个。

**Comment by fython** [comment]
已经完成。
