### ISSUE TITLE
localized app name in Play Store

### ISSUE THREAD

**Issue by udnp** [fython/Blackbulb#49]
In my environment, this app name has been default name "Night Screen", not "夜用画面" as Japanese translated name.
![nightscreen-playstore-ja](https://user-images.githubusercontent.com/17121615/33173795-c8ee6b1c-d098-11e7-94be-485a364b9c98.png)

But the installed app name is localized name.
![nightscreen-in-homes-ja](https://user-images.githubusercontent.com/17121615/33174117-fb4de7c6-d099-11e7-8f92-c158014c2b87.png)

Therefore, users may not be able to find this app in their apps list.

So I think it would be better for this app name in Play Store to be localized. 
It seems that Google Play Developer Console provides the settings to localize app name in Play Store.

Thanks.

**Comment by fython** [comment]
I updated Japanese translation in Play Store just now. Latest information will be displayed soon.

Short description and full description is not optional strings. Temporarily, I wrote them by Google translate. If translation has any problem, please inform me what problem it has. Providing the way to correct them is better.

**Comment by udnp** [comment]
Thanks for fast work.
I've confirmed updated it in Play Store. 

> If translation has any problem, please inform me what problem it has. 

Sure. I will try and inform it at this conversation. 😃 
Please just a moment.

**Comment by udnp** [comment]
I checked both translated Japanese descriptions and English them, 
then I translated my Japanese descriptions.
If would you like, use following. 😄 

Short description

> Protect your eyes from being hurt by screen at night

夜に画面を見ているときのダメージからあなたの目を守ります

Full description

> 「Night Screen」is a Material Design Application which can protect your eyes from being hurt by screen, creating a mask at the top of screen in order to make screen darker.
We can solve the problem that the lowest brightness is not low enough in some devices.
(PS: Even though you are using our application to make screen darker, you should reduce the time watching screen in a dark environment.)

「夜用画面」はマテリアルデザインのアプリで、画面を見ているときのダメージからあなたの目を守り、明るさを抑えるために画面上をマスクします。最小設定の明るさでもまだ輝度が強い機種に対しても役立ちます。（※このアプリを使用して画面を暗くしても、暗いところで画面を長時間見るのは控えてください。）

> ( Enable permission in Android 6.0: "Settings" app - "Apps" - The gear icon - "Draw over other apps" - "Night Screen" - Then enable it )

（Android 6.0 で権限を許可するには : [設定] - [アプリ] - 歯車アイコン - [他のアプリの上に表示] - [夜用画面] - そこで権限を許可します）

> Otherwise, this application is open source under GNU GPL v3 License.
> Github Repo: https://github.com/fython/Blackbulb

その他、このアプリはオープンソースで GNU GPL v3 ライセンスを基にしています。
Github Repo: https://github.com/fython/Blackbulb

**Comment by fython** [comment]
Thanks for correcting the translation. I have updated them on Play Store.

**Comment by udnp** [comment]
Thanks. I've confirmed this issue is resolved in Play Store.
