### ISSUE TITLE
Improve notification

### ISSUE THREAD

**Issue by M2ck** [fython/Blackbulb#7]
Could you implement Stop and Pause/Resume actions instead of Turn off only?
See my mockup below, thanks.

![screenshot_2016-03-10-19-00-39](https://cloud.githubusercontent.com/assets/6850125/13872657/6a55327a-ecec-11e5-8c70-d659814410ee.png)

**Comment by xwhboy** [comment]
I don't think that it is a good idea to change the button function as what you has said.

**Comment by fython** [comment]
@xwhboy I think it necessary to add a pause button.
Android System won't allow user to click "Install" in package installer when there is a overlay window.

**Comment by xwhboy** [comment]
I  met this situation when I used this app. But I think we can close it easily. Only one Button is elegant.

**Comment by fython** [comment]
@xwhboy Maybe we can learn the logic of Play Music App:
Set a "STOP" button here. Stop the filter when we click it, but its notification won't disappear at once. Only if it has been stopped can we swipe to dismiss the notification.

**Comment by M2ck** [comment]
>Set a "STOP" button here. Stop the filter when we click it, but its notification won't disappear at once. Only if it has been stopped can we swipe to dismiss the notification.

I second this, it's a good compromise IMO.

**Comment by Salamandar** [comment]
A slider may be added as well to prevent creating a new window (and thus pausing a movie whon you switch to the slider window)

**Comment by M2ck** [comment]
Well can be closed now, thanks.
