### ISSUE TITLE
Improve discrete slider

### ISSUE THREAD

**Issue by M2ck** [fython/Blackbulb#8]
Could you please add % sign to the popup, see example below.

![screenshot_2016-03-15-15-29-48](https://cloud.githubusercontent.com/assets/6850125/13872722/b5f887c2-ecec-11e5-8a8e-9d91f93a99cd.png)

**Comment by TPS** [comment]
Also, a way to type in manually, e.g., 90%?

**Comment by fython** [comment]
Night Screen's UI will be re-designed in the future. This issue is out-of-date. Thanks for your suggestion.
